# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_datetime', models.DateTimeField(auto_now_add=True)),
                ('winner', models.CharField(blank=True, choices=[('PLAYER_ONE', 'Player One'), ('PLAYER_TWO', 'Player Two'), ('PLAYER_THREE', 'Player Three'), ('PLAYER_FOUR', 'Player Four')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuessQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('filename', models.CharField(max_length=510)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameservice.Track'),
        ),
    ]
