# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def initial_match_terms(apps, schema_editor):
    Track = apps.get_model('gameservice', 'Track')
    for track in Track.objects.all():
        track.match_terms = ',%s,%s,' % (track.artist, track.title)

        for ch in '-\'!.':
            track.match_term = track.match_term.replace(ch, '')

        track.match_term = track.match_term.lower()

        track.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gameservice', '0002_guessqueue_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='match_terms',
            field=models.CharField(default='.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='track',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gameservice.Track'),
        ),
        migrations.RunPython(initial_match_terms),
    ]
